# Generated by Django 4.1.3 on 2022-11-04 12:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Имя')),
                ('patronymic', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('surname', models.CharField(blank=True, max_length=100, verbose_name='Фамилия')),
                ('FIO', models.CharField(blank=True, max_length=100, verbose_name='ФИО')),
                ('FIO_otkogo', models.CharField(blank=True, max_length=100, verbose_name='ФИО от кого')),
                ('FIO_komy', models.CharField(blank=True, max_length=100, verbose_name='ФИО кому')),
                ('office_apteka', models.SmallIntegerField(choices=[(1, 'Офис'), (2, 'Аптека')], verbose_name='poz')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Польователь')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
                'ordering': ['FIO'],
            },
        ),
    ]
