# Generated by Django 4.1.3 on 2022-11-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_office_apteka_alter_staff_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobtitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.CreateModel(
            name='SubDivision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=250, verbose_name='Подразделение')),
            ],
            options={
                'verbose_name': 'Подразделение',
                'verbose_name_plural': 'Подразделения',
            },
        ),
        migrations.AlterField(
            model_name='staff',
            name='office_apteka',
            field=models.CharField(choices=[('OF', 'Офис'), ('APT', 'Аптека')], default='OF', max_length=10, verbose_name='Офис или аптека'),
        ),
    ]
