# Generated by Django 4.1.3 on 2022-11-04 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_jobtitle_subdivision_alter_staff_office_apteka'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='job_title',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='JobTitle', to='staff.jobtitle', verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='staff',
            name='sub_division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='SubDivision', to='staff.subdivision', verbose_name='Подразделение'),
        ),
    ]
