# Generated by Django 4.1.3 on 2022-11-03 06:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='lk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='Пользователь', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь ЛК')),
            ],
            options={
                'verbose_name': 'Личный кабинет',
                'verbose_name_plural': 'Кабинеты пользователей',
                'ordering': ['user'],
            },
        ),
    ]
