# Generated by Django 4.1.3 on 2022-11-03 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lk', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lk',
            options={'ordering': ['time_add'], 'verbose_name': 'Личный кабинет', 'verbose_name_plural': 'Кабинеты пользователей'},
        ),
        migrations.AddField(
            model_name='lk',
            name='time_add',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 11, 3, 7, 6, 5, 46387, tzinfo=datetime.timezone.utc), verbose_name='Дата время создания'),
            preserve_default=False,
        ),
    ]
